### ISSUE TITLE
install script for server in root package.json is broken

### ISSUE THREAD

**Issue by alastair87** [CodeYourFuture/ubuntu#23]
The start and install scripts for the server in the root package.json are incorrect. This causes `npm install` from the root of the project to fail for the server portion of the installation:

Failure trace:

```
■ ~/CodeYourFuture/ubuntu
▶ npm install

> ubuntu@1.0.0 install /home/alastair/CodeYourFuture/ubuntu
> npm --prefix server start install & npm --prefix client install


> server@1.0.0 start /home/alastair/CodeYourFuture/ubuntu/server
> node app.js "install"

module.js:549
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/alastair/CodeYourFuture/ubuntu/server/app.js:2:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! server@1.0.0 start: `node app.js "install"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the server@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alastair/.npm/_logs/2018-08-17T15_17_01_320Z-debug.log
```

The client portion of the installation completes successfully:

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1328 packages from 815 contributors and audited 14336 packages in 16.922s
found 0 vulnerabilities

up to date in 17.576s
found 0 vulnerabilities
```

If the installation for server is performed manually from the server folder the installation completes successfully:

 ```
■ ~/CodeYourFuture/ubuntu/server
 ▶ npm install

> sqlite3@4.0.2 install /home/alastair/CodeYourFuture/ubuntu/server/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
[sqlite3] Success: "/home/alastair/CodeYourFuture/ubuntu/server/node_modules/sqlite3/lib/binding/node-v57-linux-x64/node_sqlite3.node" is installed via remote

> nodemon@1.18.3 postinstall /home/alastair/CodeYourFuture/ubuntu/server/node_modules/nodemon
> node bin/postinstall || exit 0

npm WARN server@1.0.0 No description
npm WARN server@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 455 packages from 297 contributors and audited 2718 packages in 8.647s
found 0 vulnerabilities
```

Once the server is installed however, `npm start` from the root successfully starts both client and server.

The issue appears to be simply that the install instruction for the server should be `npm prefix --server install`, not `npm prefix --server start install`.

The testing environment is Linux Mint 19, node v8.11.4, npm 6.4.0 however these are in my view not likely to be important for this issue.

**Comment by rarmatei** [comment]
@alastair87 is this still an issue? Seemed to work for me.
